# Generated by Django 5.2.3 on 2025-06-21 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_stock_id_alter_stock_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='uuid',
        ),
    ]
