# Generated by Django 5.2.3 on 2025-06-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_stock_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessusers',
            name='email',
            field=models.EmailField(default=None, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessusers',
            name='password',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
