# Generated by Django 5.2.3 on 2025-06-21 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_businessusers_email_businessusers_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='CutomerUser',
            fields=[
                ('uuid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('due_date', models.DateTimeField(auto_now_add=True)),
                ('business_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='myapp.businessusers')),
                ('customer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='myapp.cutomeruser')),
            ],
        ),
    ]
