# Generated by Django 5.2.3 on 2025-06-22 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_cutomeruser_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessusers',
            name='name',
            field=models.CharField(default='John Doe', max_length=100),
        ),
    ]
