# Generated by Django 5.2.3 on 2025-06-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_businessusers_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='id',
        ),
        migrations.AddField(
            model_name='credit',
            name='credit_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='credit',
            name='paid_status',
            field=models.BooleanField(default=False),
        ),
    ]
