# Generated by Django 5.2.3 on 2025-06-22 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_businessusers_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='id',
        ),
        migrations.AddField(
            model_name='credit',
            name='credit_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='credit',
            name='paid_status',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('business_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='myapp.businessusers')),
            ],
        ),
    ]
